"""correct item requirements

Revision ID: 21ae08415927
Revises: 6134f340a2ee
Create Date: 2026-05-05 17:45:02.026019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ae08415927'
down_revision: Union[str, Sequence[str], None] = '6134f340a2ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('required_lvl', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'skill_id', name='unique_item_skill')
    )
    op.drop_table('items_to_skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_to_skills',
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('required_lvl', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('items_to_skills_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('items_to_skills_skill_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'skill_id', name=op.f('items_to_skills_pkey'))
    )
    op.drop_table('item_requirements')
    # ### end Alembic commands ###
