"""unique stuff

Revision ID: 5043df1dfc67
Revises: 9ce75d581712
Create Date: 2026-05-08 18:22:09.878980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5043df1dfc67'
down_revision: Union[str, Sequence[str], None] = '9ce75d581712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_item_for_inventory', 'inventory', ['user_id', 'item_id'])
    op.create_unique_constraint('unique_user_item_for_shop', 'shop', ['user_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_item_for_shop', 'shop', type_='unique')
    op.drop_constraint('unique_user_item_for_inventory', 'inventory', type_='unique')
    # ### end Alembic commands ###
