"""fix shop_transaction table

Revision ID: 0af101746e37
Revises: 6abf4dfa96f7
Create Date: 2026-06-13 18:23:11.744994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af101746e37'
down_revision: Union[str, Sequence[str], None] = '6abf4dfa96f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_transaction', 'shop_listing_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shop_transaction', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop_transaction', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('shop_transaction', 'shop_listing_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
