"""init

Revision ID: 1a08ecaab860
Revises: 
Create Date: 2026-03-29 19:47:01.476876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a08ecaab860'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'item_id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('rank', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'type',
               existing_type=postgresql.ENUM('CUSTOM', 'AUTO', name='task_type'),
               nullable=True)
    op.alter_column('task', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', 'EPIC', name='task_difficulty'),
               nullable=True)
    op.alter_column('task', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               nullable=True)
    op.alter_column('task', 'custom_xp_reward',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('task', 'custom_gold_reward',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('user', sa.Column('gold', sa.BigInteger(), nullable=True))
    op.execute('UPDATE "user" SET gold = 0')
    op.alter_column('user', 'gold', nullable=False)
    op.create_foreign_key(None, 'user', 'rank', ['current_rank_id'], ['id'])
    op.drop_column('user', 'money')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('money', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'gold')
    op.alter_column('task', 'custom_gold_reward',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('task', 'custom_xp_reward',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('task', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'),
               nullable=False)
    op.alter_column('task', 'difficulty',
               existing_type=postgresql.ENUM('EASY', 'MEDIUM', 'HARD', 'EPIC', name='task_difficulty'),
               nullable=False)
    op.alter_column('task', 'type',
               existing_type=postgresql.ENUM('CUSTOM', 'AUTO', name='task_type'),
               nullable=False)
    op.alter_column('rank', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('shop')
    op.drop_table('inventory')
    # ### end Alembic commands ###
