"""relations and minor changes

Revision ID: 6134f340a2ee
Revises: 1a08ecaab860
Create Date: 2026-04-25 17:55:57.378678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6134f340a2ee'
down_revision: Union[str, Sequence[str], None] = '1a08ecaab860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('item_usage_history_pkey', 'item_usage_history', type_='primary')
    op.add_column('item_usage_history', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('item_usage_history', 'item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_primary_key('item_usage_history_pkey', 'item_usage_history', ['id'])
    op.alter_column('task', 'type',
               existing_type=postgresql.ENUM('CUSTOM', 'AUTO', name='task_type'),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'type',
               existing_type=postgresql.ENUM('CUSTOM', 'AUTO', name='task_type'),
               nullable=True)
    op.alter_column('item_usage_history', 'item_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('item_usage_history', 'id')
    # ### end Alembic commands ###
