"""new shop_transaction table

Revision ID: 6abf4dfa96f7
Revises: 5043df1dfc67
Create Date: 2026-06-13 18:12:36.711170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abf4dfa96f7'
down_revision: Union[str, Sequence[str], None] = '5043df1dfc67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_transaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('shop_listing_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('item_title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_listing_id'], ['shop.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_transaction')
    # ### end Alembic commands ###
