from typing import Protocol, Optional

class RedisRepositoryProtocol(Protocol):
    async def create_session(self, user_id: str) -> str: ...
    async def extend_token_time(self, session_token: str) -> None: ...
    async def delete_session(self, session_token: str) -> None: ...
    async def get_user_id_by_session_token(self, session_token: str) -> Optional[str]: ...
    async def get_session_time(self, session_token: str) -> int: ...