from typing import Protocol, Optional, Sequence
from src.app.domain import Item, User, Task, Skill, Inventory, TaskHistory, TaskCategory
from uuid import UUID 
from src.app.application.dto import TaskFilterParamsDTO, TaskSortParamsDTO
from src.app.domain.value_objects import TaskReward

class UserRepositoryProtocol(Protocol): 
    async def get_all_users(self, limit: int, offset: int) -> Sequence[User]: ...
    async def get_user(self, user_id: UUID) -> Optional[User]: ...
    async def get_user_by_username(self, username: str) -> Optional[User]: ...
    async def get_user_by_email(self, email: str) -> Optional[User]: ...
    def save(self, user: User) -> None: ...
    async def delete(self, user_id: UUID) -> None: ...
    async def does_username_exists(self, username: str) -> Optional[bool]: ...
    async def does_email_exists(self, email: str) -> Optional[bool]: ...

class TaskRepositoryProtocol(Protocol): 
    async def get_all_tasks(self, filters: TaskFilterParamsDTO, sorting: TaskSortParamsDTO, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_tasks_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_task_by_id(self, task_id: UUID) -> Optional[Task]: ...
    async def get_tasks_by_skill_id(self, skill_id: UUID) -> Sequence[Task]: ...
    async def get_deleted_tasks_by_user_id(self, user_id: UUID) -> Sequence[Task]: ...
    async def get_daily_tasks_by_user_id(self, user_id: UUID) -> Sequence[Task]: ...
    async def get_todays_deadline_tasks_by_user_id(self, user_id: UUID) -> Sequence[Task]: ...
    async def get_overdue_tasks_by_user_id(self, user_id: UUID) -> Sequence[Task]: ...
    async def get_tasks_by_category_id(self, task_category: UUID) -> Sequence[Task]: ...
    async def delete(self, task_id: UUID) -> None: ...
    async def delete_all_tasks_deleted_more_than_year(self) -> None: ...

class TaskCategoriesRepositoryProtocol(Protocol):
    async def get_all_task_categories(self) -> Sequence[TaskCategory]: ...
    async def get_current_user_task_categories(self, user_id: UUID) -> Sequence[TaskCategory]: ...
    async def get_task_category_by_id(self, task_category_id: UUID) -> Optional[TaskCategory]: ...
    async def delete_current_user_task_category_by_id(self, task_category_id: UUID) -> None: ...

class TaskHistoryRepositoryProtocol(Protocol):
    async def get_recent_history_with_skills(self, task_id: UUID, limit: int) -> Sequence[TaskHistory]: ...
    async def save_completion(self, task: Task, skills: Sequence[Skill], rewards: TaskReward) -> None: ...

class SkillRepositoryProtocol(Protocol): 
    async def get_all_skills(self, limit: int, offset: int) -> Sequence[Skill]: ... 
    async def get_skills_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Skill]: ...
    async def get_skill_by_id(self, skill_id: UUID) -> Optional[Skill]: ... 
    async def delete_all_skills_deleted_more_than_year(self) -> None: ...
    async def get_skills_by_task_id(self, task_id: UUID) -> Sequence[Skill]: ...

class ItemRepositoryProtocol(Protocol): 
    async def get_all_items(self, limit: int, offset: int) -> Sequence[Item]: ... 
    async def get_items_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Item]: ...
    async def get_item_by_id(self, item_id: UUID) -> Optional[Item]: ...  
    async def delete(self, item_id: UUID): ...
    async def get_items_by_task_id(self, task_id: UUID) -> Sequence[Item]: ...

class InventoryRepositoryProtocol(Protocol):
    async def get_items_in_inventory_by_user_id(self, user_id: str, offset: int, limit: int) -> Sequence[Inventory]: ...
    async def delete_item(self, item_id: UUID) -> None: ...

