from typing import Protocol
from src.app.infrastructure.database.models import Base

class TransactionProtocol(Protocol):
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def save(self, model: Base) -> None: ...
    async def delete(self, model: Base) -> None: ...