from typing import Protocol, Optional, Sequence
from sqlalchemy import ColumnExpressionArgument, ScalarResult
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.base import Base
from app.models import Item, User, Task, Skill
from uuid import UUID

class UserRepositoryProtocol(Protocol): 
    async def get_all_users(self, limit: int, offset: int) -> Sequence[User]: ...
    async def get_user(self, user_id: UUID) -> Optional[User]: ...
    async def get_user_by_username(self, username: str) -> Optional[User]: ...
    async def get_user_by_email(self, email: str) -> Optional[User]: ...
    def save(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def does_username_exists(self, username: str) -> Optional[bool]: ...
    async def does_email_exists(self, email: str) -> Optional[bool]: ...

class TaskRepositoryProtocol(Protocol): 
    async def get_all_tasks(self, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_tasks_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_task_with_user(self, task_id: UUID) -> Optional[Task]: ...
    def save(self, task: Task) -> None: ...
    async def get_task_by_id(self, task_id: UUID) -> Optional[Task]: ...
    async def delete(self, task: Task) -> None: ...

class SkillRepositoryProtocol(Protocol): 
    async def get_all_skills(self, limit: int, offset: int) -> Sequence[Skill]: ... 
    async def get_skills_by_user_id(self, user_id, limit: int, offset: int) -> Sequence[Skill]: ...
    async def get_skill_by_id(self, skill_id) -> Optional[Skill]: ...  
    def save(self, skill: Skill): ...
    async def delete(self, skill: Skill): ...

class ItemRepositoryProtocol(Protocol): 
    async def get_all_items(self, limit: int, offset: int) -> Sequence[Item]: ... 
    async def get_items_by_user_id(self, user_id, limit: int, offset: int) -> Sequence[Item]: ...
    async def get_item_by_id(self, item_id) -> Optional[Item]: ...  
    def save(self, item: Item): ...
    async def delete(self, item: Item): ...

class RedisRepositoryProtocol(Protocol):
    async def create_session(self, user_id: str) -> str: ...
    async def delete_session(self, session_id) -> None: ...
    async def get_user_id_by_session_id(self, session_id) -> UUID: ...