from typing import Protocol, Optional, Sequence
from app.models import Item, User, Task, Skill, Inventory, Base, TaskHistory
from uuid import UUID
from app.schemas.dto import TaskFilterParamsDTO, TaskSortParamsDTO

class UserRepositoryProtocol(Protocol): 
    async def get_all_users(self, limit: int, offset: int) -> Sequence[User]: ...
    async def get_user(self, user_id: UUID) -> Optional[User]: ...
    async def get_user_by_username(self, username: str) -> Optional[User]: ...
    async def get_user_by_email(self, email: str) -> Optional[User]: ...
    def save(self, user: User) -> None: ...
    async def delete(self, user: User) -> None: ...
    async def does_username_exists(self, username: str) -> Optional[bool]: ...
    async def does_email_exists(self, email: str) -> Optional[bool]: ...

class TaskRepositoryProtocol(Protocol): 
    async def get_all_tasks(self, filters: TaskFilterParamsDTO, sorting: TaskSortParamsDTO, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_tasks_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Task]: ...
    async def get_task_with_user(self, task_id: UUID) -> Optional[Task]: ...
    async def get_task_by_id(self, task_id: UUID, get_related_skills: bool, get_related_items: bool) -> Optional[Task]: ...
    async def get_task_with_user_and_skills(self, task_id: UUID) -> Optional[Task]: ...

class TaskHistoryRepositoryProtocol(Protocol):
    async def get_recent_history_with_skills(self, task_id: UUID, limit: int) -> Sequence[TaskHistory]: ...

class SkillRepositoryProtocol(Protocol): 
    async def get_all_skills(self, limit: int, offset: int) -> Sequence[Skill]: ... 
    async def get_skills_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Skill]: ...
    async def get_skill_by_id(self, skill_id: UUID) -> Optional[Skill]: ...  
    async def delete_all_skills_deleted_more_than_year(self) -> None: ...

class ItemRepositoryProtocol(Protocol): 
    async def get_all_items(self, limit: int, offset: int) -> Sequence[Item]: ... 
    async def get_items_by_user_id(self, user_id: UUID, limit: int, offset: int) -> Sequence[Item]: ...
    async def get_item_by_id(self, item_id: UUID) -> Optional[Item]: ...  
    async def delete(self, item_id: UUID): ...

class InventoryRepositoryProtocol(Protocol):
    async def get_items_in_inventory_by_user_id(self, user_id: str, offset: int, limit: int) -> Sequence[Inventory]: ...
    async def delete_item(self, item_id: UUID) -> None: ...

class RedisRepositoryProtocol(Protocol):
    async def create_session(self, user_id: str) -> str: ...
    async def extend_token_time(self, session_token: str) -> None: ...
    async def delete_session(self, session_token: str) -> None: ...
    async def get_user_id_by_session_token(self, session_token: str) -> Optional[str]: ...
    async def get_session_time(self, session_token: str) -> int: ...

class TransactionProtocol(Protocol):
    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def save(self, model: Base) -> None: ...
    async def delete(self, model: Base) -> None: ...